import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div>
      <p>Hello {{ title }}</p>
    </div>
    <app-test-comp1></app-test-comp1>
    <app-test-comp2></app-test-comp2>
    <app-test-comp3></app-test-comp3>
    <app-test-comp4></app-test-comp4>
    <app-test-comp5></app-test-comp5>
    <app-test-comp6></app-test-comp6>
    <app-test-comp7></app-test-comp7>
    <app-test-comp8></app-test-comp8>
    <app-test-comp9></app-test-comp9>
    <app-test-comp10></app-test-comp10>
    <app-test-comp11></app-test-comp11>
    <app-test-comp12></app-test-comp12>
    <app-test-comp13></app-test-comp13>
    <app-test-comp14></app-test-comp14>
    <app-test-comp15></app-test-comp15>
    <app-test-comp16></app-test-comp16>
    <app-test-comp17></app-test-comp17>
    <app-test-comp18></app-test-comp18>
    <app-test-comp19></app-test-comp19>
    <app-test-comp20></app-test-comp20>
    <app-test-comp21></app-test-comp21>
    <app-test-comp22></app-test-comp22>
    <app-test-comp23></app-test-comp23>
    <app-test-comp24></app-test-comp24>
    <app-test-comp25></app-test-comp25>
    <app-test-comp26></app-test-comp26>
    <app-test-comp27></app-test-comp27>
    <app-test-comp28></app-test-comp28>
    <app-test-comp29></app-test-comp29>
    <app-test-comp30></app-test-comp30>
    <app-test-comp31></app-test-comp31>
    <app-test-comp32></app-test-comp32>
    <app-test-comp33></app-test-comp33>
    <app-test-comp34></app-test-comp34>
    <app-test-comp35></app-test-comp35>
    <app-test-comp36></app-test-comp36>
    <app-test-comp37></app-test-comp37>
    <app-test-comp38></app-test-comp38>
    <app-test-comp39></app-test-comp39>
    <app-test-comp40></app-test-comp40>
    <app-test-comp41></app-test-comp41>
    <app-test-comp42></app-test-comp42>
    <app-test-comp43></app-test-comp43>
    <app-test-comp44></app-test-comp44>
    <app-test-comp45></app-test-comp45>
    <app-test-comp46></app-test-comp46>
    <app-test-comp47></app-test-comp47>
    <app-test-comp48></app-test-comp48>
    <app-test-comp49></app-test-comp49>
    <app-test-comp50></app-test-comp50>
    <app-test-comp51></app-test-comp51>
    <app-test-comp52></app-test-comp52>
    <app-test-comp53></app-test-comp53>
    <app-test-comp54></app-test-comp54>
    <app-test-comp55></app-test-comp55>
    <app-test-comp56></app-test-comp56>
    <app-test-comp57></app-test-comp57>
    <app-test-comp58></app-test-comp58>
    <app-test-comp59></app-test-comp59>
    <app-test-comp60></app-test-comp60>
    <app-test-comp61></app-test-comp61>
    <app-test-comp62></app-test-comp62>
    <app-test-comp63></app-test-comp63>
    <app-test-comp64></app-test-comp64>
    <app-test-comp65></app-test-comp65>
    <app-test-comp66></app-test-comp66>
    <app-test-comp67></app-test-comp67>
    <app-test-comp68></app-test-comp68>
    <app-test-comp69></app-test-comp69>
    <app-test-comp70></app-test-comp70>
    <app-test-comp71></app-test-comp71>
    <app-test-comp72></app-test-comp72>
    <app-test-comp73></app-test-comp73>
    <app-test-comp74></app-test-comp74>
    <app-test-comp75></app-test-comp75>
    <app-test-comp76></app-test-comp76>
    <app-test-comp77></app-test-comp77>
    <app-test-comp78></app-test-comp78>
    <app-test-comp79></app-test-comp79>
    <app-test-comp80></app-test-comp80>
    <app-test-comp81></app-test-comp81>
    <app-test-comp82></app-test-comp82>
    <app-test-comp83></app-test-comp83>
    <app-test-comp84></app-test-comp84>
    <app-test-comp85></app-test-comp85>
    <app-test-comp86></app-test-comp86>
    <app-test-comp87></app-test-comp87>
    <app-test-comp88></app-test-comp88>
    <app-test-comp89></app-test-comp89>
    <app-test-comp90></app-test-comp90>
    <app-test-comp91></app-test-comp91>
    <app-test-comp92></app-test-comp92>
    <app-test-comp93></app-test-comp93>
    <app-test-comp94></app-test-comp94>
    <app-test-comp95></app-test-comp95>
    <app-test-comp96></app-test-comp96>
    <app-test-comp97></app-test-comp97>
    <app-test-comp98></app-test-comp98>
    <app-test-comp99></app-test-comp99>
    <app-test-comp100></app-test-comp100>
  `
})
export class AppComponent {
  title = 'World';

  updateTitle() {
    this.title = 'Luxembourg !';
  }
}
